### ISSUE TITLE
multiple samplingfeatures for one nivabase station_id cause errors

### ISSUE THREAD

**Issue by haakondr** [NIVANorge/odm2-postgres-api#201]
we get the following stacktrace:

```
Traceback (most recent call last):
  File "/app/kafka_sink/message_handlers.py", line 333, in project_post_processing
    await save_project_station(conn, msg)
  File "/app/kafka_sink/message_handlers.py", line 364, in save_project_station
    samplingfeature = await connection.fetchrow(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 679, in fetchrow
    data = await self._execute(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 1731, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.CardinalityViolationError: more than one row returned by a subquery used as an expression
```

There are some stations which map to multiple samplingfeatures:

```
select samplingfeatureexternalidentifier, count(*) from odm2.samplingfeatureexternalidentifiers group by samplingfeatureexternalidentifier order by count(*) desc
```

| samplingfeatureexternalidentifier | count |
| :--- | :--- |
| 73526 | 3 |
| 73554 | 2 |
| 73564 | 2 |
| 73536 | 2 |
| 73562 | 2 |
| 73561 | 2 |
| 73556 | 2 |
| 73523 | 2 |
| 73555 | 2 |
| 73560 | 2 |
| 73570 | 2 |
 

example:

| bridgeid | samplingfeatureid | externalidentifiersystemid | samplingfeatureexternalidentifier | samplingfeatureexternalidentifieruri |
| :--- | :--- | :--- | :--- | :--- |
| 61400 | 61927 | 2 | 73526 | NULL |
| 61401 | 61928 | 2 | 73526 | NULL |
| 61402 | 61929 | 2 | 73526 | NULL |

This is related to https://github.com/NIVANorge/odm2-postgres-api/issues/195. in #195 we added unique constraints for `(samplingfeatureid, externalidentifiersystemid)` but I realize that we need a unique constraint on `(samplingfeatureexternalidentifier, externalidentifiersystemid)` as well

**Comment by haakondr** [comment]
I think these data were created when multiple messages with same key appeared in the same batch. Fixed by #198 but we need to cleanup data. Suggest the following:

- add unique constraints on the following:

```
alter table odm2.SamplingFeatureExternalIdentifiers add unique(samplingfeatureexternalidentifier, externalidentifiersystemid)
alter table odm2.ProjectStationExternalIdentifiers add unique(projectstationexternalidentifier, externalidentifiersystemid)
alter table odm2.ProjectExternalIdentifiers add unique(projectexternalidentifier, externalidentifiersystemid)
```

- cleanup and reingest data using the delete procedure defined in https://github.com/NIVANorge/odm2-postgres-api/issues/197#issuecomment-1025544758
